# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccs < Formula
  desc "Search and resume Claude Code conversations"
  homepage "https://github.com/agentic-utils/ccs"
  version "0.27.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentic-utils/ccs/releases/download/v0.27.2/ccs_darwin_amd64.tar.gz"
      sha256 "5671931ee60135727db4b7ccdcafb327765b0e0023bb256bfa88535063190979"

      define_method(:install) do
        bin.install "ccs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentic-utils/ccs/releases/download/v0.27.2/ccs_darwin_arm64.tar.gz"
      sha256 "fa6b4f45a8c60572e43cf75b184505b87bdb433ee91bf21ce0a3580f00b0f591"

      define_method(:install) do
        bin.install "ccs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-utils/ccs/releases/download/v0.27.2/ccs_linux_amd64.tar.gz"
      sha256 "d998a34d31ed8c4b6ba39aa58a20d322b6bc74296307333493364af3f4da6a95"
      define_method(:install) do
        bin.install "ccs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-utils/ccs/releases/download/v0.27.2/ccs_linux_arm64.tar.gz"
      sha256 "51d94523d9d3aadb738bd5dbe5d970816f01e1b68e2e47988655a081c870ec20"
      define_method(:install) do
        bin.install "ccs"
      end
    end
  end

  test do
    system "#{bin}/ccs", "--version"
  end
end
