# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zeltapp < Formula
  desc "Unofficial CLI for the Zelt HR platform"
  homepage "https://github.com/agentic-utils/zeltapp-cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentic-utils/zeltapp-cli/releases/download/v0.0.1/zeltapp_darwin_amd64.tar.gz"
      sha256 "530eb076ae16bd1524f323f149ecb67cff7cb61bebcd9800a0eca415e68ff71d"

      define_method(:install) do
        bin.install "zeltapp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentic-utils/zeltapp-cli/releases/download/v0.0.1/zeltapp_darwin_arm64.tar.gz"
      sha256 "a075d0c98cd07c12f0bbc0783402e0c375b8cc7c21ec5d51c8f2a87393deb371"

      define_method(:install) do
        bin.install "zeltapp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-utils/zeltapp-cli/releases/download/v0.0.1/zeltapp_linux_amd64.tar.gz"
      sha256 "bd0b8b0a93fe716e11ac2bc0aad6b9bca7c08aa5b533ce399a4b3615eb69945a"
      define_method(:install) do
        bin.install "zeltapp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-utils/zeltapp-cli/releases/download/v0.0.1/zeltapp_linux_arm64.tar.gz"
      sha256 "11d43054c0c9b90e3ad485f80094d2dc3394d53986eded4af03d81c70a719a94"
      define_method(:install) do
        bin.install "zeltapp"
      end
    end
  end

  test do
    system "#{bin}/zeltapp", "--version"
  end
end
