# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zeltapp < Formula
  desc "Unofficial CLI for the Zelt HR platform"
  homepage "https://github.com/agentic-utils/zeltapp-cli"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agentic-utils/zeltapp-cli/releases/download/v0.0.3/zeltapp_darwin_amd64.tar.gz"
      sha256 "7bed834b442b7a9f78918616c6a0bbca430d9d6959189c6b68f81a1b6981e1a7"

      define_method(:install) do
        bin.install "zeltapp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agentic-utils/zeltapp-cli/releases/download/v0.0.3/zeltapp_darwin_arm64.tar.gz"
      sha256 "12ebaf28e46c6bcd5239abe31bb4bf1e5376f9dcb555a4e2f4fc8b932f2c3aaa"

      define_method(:install) do
        bin.install "zeltapp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-utils/zeltapp-cli/releases/download/v0.0.3/zeltapp_linux_amd64.tar.gz"
      sha256 "6f680038c3e1773c29e0ff8dceec794f4e331404d3d0c6e22fc17588993a5a27"
      define_method(:install) do
        bin.install "zeltapp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agentic-utils/zeltapp-cli/releases/download/v0.0.3/zeltapp_linux_arm64.tar.gz"
      sha256 "beb67a9fc8157a33e93c57e5d300a1394b0d012fa7ead2e93b2e4f4d94d241c5"
      define_method(:install) do
        bin.install "zeltapp"
      end
    end
  end

  test do
    system "#{bin}/zeltapp", "--version"
  end
end
